package com.agency.provider.avianca;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-05-28T19:21:27.615-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "AviancaService", 
                  wsdlLocation = "http://localhost:8085/avianca?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class AviancaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "AviancaService");
    public final static QName BasicHttpBindingIAviancaService = new QName("http://tempuri.org/", "BasicHttpBinding_IAviancaService");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8085/avianca?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AviancaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8085/avianca?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AviancaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AviancaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AviancaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AviancaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AviancaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AviancaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IAviancaService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAviancaService")
    public IAviancaService getBasicHttpBindingIAviancaService() {
        return super.getPort(BasicHttpBindingIAviancaService, IAviancaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAviancaService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAviancaService")
    public IAviancaService getBasicHttpBindingIAviancaService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIAviancaService, IAviancaService.class, features);
    }

}
