package com.agency.provider.avianca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-05-28T19:21:27.555-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IAviancaService")
@XmlSeeAlso({ObjectFactory.class})
public interface IAviancaService {

    @WebMethod(operationName = "Quote", action = "http://tempuri.org/IAviancaService/Quote")
    @Action(input = "http://tempuri.org/IAviancaService/Quote", output = "http://tempuri.org/IAviancaService/QuoteResponse")
    @RequestWrapper(localName = "Quote", targetNamespace = "http://tempuri.org/", className = "com.agency.provider.avianca.Quote")
    @ResponseWrapper(localName = "QuoteResponse", targetNamespace = "http://tempuri.org/", className = "com.agency.provider.avianca.QuoteResponse")
    @WebResult(name = "QuoteResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String quote();

    @WebMethod(operationName = "Reserve", action = "http://tempuri.org/IAviancaService/Reserve")
    @Action(input = "http://tempuri.org/IAviancaService/Reserve", output = "http://tempuri.org/IAviancaService/ReserveResponse")
    @RequestWrapper(localName = "Reserve", targetNamespace = "http://tempuri.org/", className = "com.agency.provider.avianca.Reserve")
    @ResponseWrapper(localName = "ReserveResponse", targetNamespace = "http://tempuri.org/", className = "com.agency.provider.avianca.ReserveResponse")
    @WebResult(name = "ReserveResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean reserve(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        java.lang.Integer id
    );

    @WebMethod(operationName = "Cancel", action = "http://tempuri.org/IAviancaService/Cancel")
    @Action(input = "http://tempuri.org/IAviancaService/Cancel", output = "http://tempuri.org/IAviancaService/CancelResponse")
    @RequestWrapper(localName = "Cancel", targetNamespace = "http://tempuri.org/", className = "com.agency.provider.avianca.Cancel")
    @ResponseWrapper(localName = "CancelResponse", targetNamespace = "http://tempuri.org/", className = "com.agency.provider.avianca.CancelResponse")
    @WebResult(name = "CancelResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean cancel(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        java.lang.Integer id
    );
}
